export type GuidePost = {
  slug: string;
  title: string;
  description: string;
  publishedAt: string; // YYYY-MM-DD
  keywords: string[];
  body: string;
};

export const GUIDES: GuidePost[] = [
  {
    slug: "quote-template-small-business",
    title: "Quote template for small business (mobile-first)",
    description:
      "A practical quoting template for SMBs: line items, scope, validity, payment terms, and how to send a clean PDF or share link.",
    publishedAt: "2026-04-09",
    keywords: ["quote template", "quotation template", "small business quote", "mobile quoting"],
    body: [
      "## Why templates beat Word/Excel",
      "Most SMB quote mistakes come from copy‑paste: outdated pricing, missing terms, and version confusion. A consistent template reduces back‑and‑forth and speeds up approvals.",
      "",
      "## What a good quote should include",
      "- **Seller & buyer details**: legal name, address, contact, tax ID if applicable.",
      "- **Quote number & date**: unique ID for easy follow‑up.",
      "- **Line items**: item name, model/spec, unit, qty, unit price, amount, notes.",
      "- **Totals**: subtotal, taxes (sales tax/VAT), fees, grand total.",
      "- **Validity**: \"Valid until\" date (creates urgency and prevents stale pricing).",
      "- **Payment terms**: due date, accepted methods, late fees (optional).",
      "- **Delivery / timeline**: lead time, milestones, or service window.",
      "",
      "## How to send it (US/EU style)",
      "Send a **PDF** for professionalism, and include a **read‑only link** so your customer can view on mobile without downloading.",
      "",
      "## Next step",
      "When the customer accepts, convert the quote into a contract to lock scope and reduce disputes.",
    ].join("\\n"),
  },
  {
    slug: "sales-contract-essentials-smb",
    title: "Sales contract essentials for SMBs",
    description:
      "What to include in a simple sales contract: scope, pricing, taxes, delivery, warranty, governing law, and signature blocks.",
    publishedAt: "2026-04-09",
    keywords: ["sales contract", "contract template", "SMB contract", "e-sign"],
    body: [
      "## Keep it simple, keep it enforceable",
      "For SMBs, contracts should be short and clear. The goal is to prevent misunderstandings, not to write a novel.",
      "",
      "## Core sections",
      "- **Parties**: buyer and seller legal names and addresses.",
      "- **Scope / items**: line items, quantities, service details.",
      "- **Price & payment**: totals, due dates, refunds, and chargeback handling.",
      "- **Taxes**: whether tax is included, and which tax type applies (sales tax/VAT/GST).",
      "- **Delivery**: location, timeline, risk transfer (if physical goods).",
      "- **Warranty / support**: duration and exclusions.",
      "- **Disputes**: governing law and venue (use your jurisdiction).",
      "- **Signatures**: e‑sign acceptance and date/place signed.",
      "",
      "## Practical tips",
      "- Lock the price and scope once signed.",
      "- Store a read‑only copy and export a PDF for record‑keeping.",
    ].join("\\n"),
  },
  {
    slug: "get-paid-faster-after-sign",
    title: "Get paid faster: sign → pay workflow for SMBs",
    description:
      "A lightweight workflow to reduce cashflow delays: customer signs, then pays immediately via a payment link.",
    publishedAt: "2026-04-09",
    keywords: ["get paid faster", "payment link", "SMB invoicing", "cash flow"],
    body: [
      "## The SMB cashflow problem",
      "Many deals stall after acceptance: the customer needs an invoice, finance wants a PO, and payment gets delayed.",
      "",
      "## The simplest fix: sign → pay",
      "After the customer signs (or accepts), send them directly to a **payment link**. This reduces friction and shortens the time to cash.",
      "",
      "## What to show on the payment page",
      "- Contract number and total amount",
      "- What the payment covers (short description)",
      "- Receipt/invoice email",
      "",
      "## What to track",
      "- Opened the contract link",
      "- Signed date",
      "- Payment completed",
    ].join("\\n"),
  },
  {
    slug: "quote-validity-period-us-eu",
    title: "Quote validity period: what to set (US/EU SMB playbook)",
    description:
      "How long should a quote be valid? Practical ranges for SMB deals, plus wording you can copy to avoid stale pricing.",
    publishedAt: "2026-04-09",
    keywords: ["quote validity", "valid until", "quote expiration", "SMB sales"],
    body: [
      "## Why quote validity matters",
      "A clear validity window prevents pricing disputes, creates urgency, and reduces endless revision cycles.",
      "",
      "## Common ranges (practical, not legal advice)",
      "- **7 days**: fast-moving items, volatile costs, tight delivery windows.",
      "- **14 days**: a common default for SMB quotes.",
      "- **30 days**: longer sales cycles, higher-ticket services, procurement steps.",
      "",
      "## Copy-ready wording",
      "- \"This quotation is valid until YYYY-MM-DD.\"",
      "- \"Pricing is subject to change after the validity period.\"",
      "",
      "## Tip",
      "If you offer yearly pricing or longer delivery timelines, consider a shorter validity with a clear renewal step.",
    ].join("\n"),
  },
  {
    slug: "sales-tax-vat-gst-explained",
    title: "Sales tax vs VAT vs GST: what to show on quotes and contracts",
    description:
      "A simple explanation of common tax types, and how to present tax fields clearly for US/EU customers.",
    publishedAt: "2026-04-09",
    keywords: ["sales tax", "VAT", "GST", "quote tax", "contract tax"],
    body: [
      "## The goal: clarity for your customer",
      "Your document should answer: is tax included, what rate applies, and what the total is.",
      "",
      "## Quick definitions (high-level)",
      "- **Sales tax (US)**: typically added at checkout; may depend on location and nexus rules.",
      "- **VAT (EU/UK)**: value-added tax; often shown as a separate line item; reverse charge may apply for B2B.",
      "- **GST**: similar concept used in several regions.",
      "",
      "## What to show on the document",
      "- **Tax included**: Yes/No",
      "- **Tax rate (%)**: e.g. 0, 5, 20",
      "- **Tax amount** and **Total**",
      "",
      "## Practical tip for SMBs",
      "If you’re unsure, start with **0%** and add a note like \"Tax may apply\". For scale, use a merchant‑of‑record to handle tax calculation.",
    ].join("\n"),
  },
  {
    slug: "contract-numbering-best-practices",
    title: "Contract numbering best practices (simple, searchable, auditable)",
    description:
      "A lightweight contract numbering scheme for SMBs that stays readable and scales with your volume.",
    publishedAt: "2026-04-09",
    keywords: ["contract number", "contract numbering", "agreement number", "SMB process"],
    body: [
      "## What a good contract number does",
      "It helps you and your customer reference the same document quickly and prevents duplicates.",
      "",
      "## A simple format that works",
      "- Prefix (e.g. **AGR**) + date + sequence: `AGR-YYYYMMDD-001`",
      "",
      "## Tips",
      "- Keep it short; avoid spaces.",
      "- Use the signing date (or document creation date) consistently.",
      "- Don’t embed confidential info in IDs.",
      "",
      "## Why it matters for payments",
      "Your payment link, receipt, and invoice should reference the same number to reduce finance back-and-forth.",
    ].join("\n"),
  },
  {
    slug: "move-from-word-excel-to-quote-tool",
    title: "How to move from Word/Excel to a quoting tool (without chaos)",
    description:
      "A step-by-step migration plan: templates, catalog, customer list, and version control for SMB sales teams.",
    publishedAt: "2026-04-09",
    keywords: ["Word to SaaS", "Excel quoting", "quote software", "SMB migration"],
    body: [
      "## Step 1: standardize your line item structure",
      "Make sure every quote has consistent columns: name, model/spec, unit, qty, unit price, amount, notes.",
      "",
      "## Step 2: import your product list",
      "Start with your top 20 products/services. Add the rest later.",
      "",
      "## Step 3: import customers",
      "Use a consistent customer record so you don’t retype addresses and contacts every time.",
      "",
      "## Step 4: lock a template",
      "Keep your terms in one place. Don’t let each salesperson maintain their own version.",
      "",
      "## Step 5: switch sending format",
      "Send PDF + a read-only link. This reduces version confusion and improves mobile viewing.",
    ].join("\n"),
  },
  {
    slug: "payment-link-best-practices-after-signing",
    title: "Payment link best practices after signing",
    description:
      "What to include on a payment link so SMB customers pay faster: amount, scope, receipt, and next steps.",
    publishedAt: "2026-04-09",
    keywords: ["payment link", "get paid faster", "after signing", "SMB payments"],
    body: [
      "## Keep the payment step obvious",
      "Once the customer signs, remove ambiguity: show the total amount and a single primary action: Pay now.",
      "",
      "## Must-have fields",
      "- Contract number",
      "- Total amount and currency",
      "- Short description of what’s included",
      "- Receipt email",
      "",
      "## Reduce friction",
      "- Avoid forcing account creation for payers.",
      "- Support cards and local methods when possible.",
      "",
      "## Track outcomes",
      "Track whether the link was opened and whether payment succeeded, so sales knows when to follow up.",
    ].join("\n"),
  },
];

export function getGuideBySlug(slug: string): GuidePost | null {
  return GUIDES.find((p) => p.slug === slug) ?? null;
}

